# Generated by Django 2.1 on 2018-08-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Daily Essentials', 'Daily Essentials'), ('Electronics', 'Electronics'), ('Home and Furniture', 'Home and Furniture'), ('Books', 'Books')], default='Goods', max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to='productImages/')),
            ],
        ),
    ]
